#include "stdafx.h"
#include "cEmpireColorManager.h"

using namespace Simulator;

cEmpireColorManager* cEmpireColorManager::instance = nullptr;

/// AUTOGENERATED METHODS ///

int cEmpireColorManager::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cEmpireColorManager::Release() {
	return Simulator::cStrategy::Release();
}

const char* cEmpireColorManager::GetName() const {
	return "Empire_Color_Customization::cEmpireColorManager";
}

void cEmpireColorManager::OnModeExited(uint32_t previousModeID, uint32_t newModeID)
{
}

void cEmpireColorManager::OnModeEntered(uint32_t previousModeID, uint32_t newModeID)
{
}

bool cEmpireColorManager::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
	// TODO write the valid color entries and delete the invalid from the map and the db.
}
bool cEmpireColorManager::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
	// TODO read the empire color entries.
}

bool cEmpireColorManager::WriteToXML(XmlSerializer*)
{
	return true;
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cEmpireColorManager::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void cEmpireColorManager::Initialize() {
	instance = this;
	defaultGroxColor = Math::ColorRGB(0.35f, 0.0f, 0.25f);

	PropertyListPtr managerConfigProp;
	PropManager.GetPropertyList(id("GeneralConfig"), id("EccConfig"), managerConfigProp);
	int defaultEmpireColorRuleInt;
	App::Property::GetInt32(managerConfigProp.get(), 0x1520E05F, defaultEmpireColorRuleInt);
	defaultEmpireColorRule = EmpireColorRule(defaultEmpireColorRuleInt);
}

void cEmpireColorManager::Dispose() {
	
}

void cEmpireColorManager::Update(int deltaTime, int deltaGameTime) {
	
}

cEmpireColorManager* cEmpireColorManager::Get() {
	return instance;
}

EmpireColorRule cEmpireColorManager::GetDefaultEmpireColorRule()
{
	return defaultEmpireColorRule;
}

cEmpireColorEntry* cEmpireColorManager::GetEmpireColorEntry(uint32_t empireID)
{
	auto it = empireColorEntries.find(empireID);

	if (it != empireColorEntries.end() && it->second->Valid())
	{
		return it->second.get();
	}

	return nullptr;
}

void cEmpireColorManager::SetEmpireColorEntry(Simulator::cEmpire* empire, Math::ColorRGB color)
{
	if (empire == nullptr)
	{
		return;
	}
	cEmpireColorEntry* colorEntry;
	auto it = empireColorEntries.find(empire->GetEmpireID());

	// empireColorEntry exist and it's valid.
	if (it != empireColorEntries.end() && it->second->Valid())
	{
		colorEntry = it->second.get();
	}

	else
	{
		// empireColorEntry exist but isn't valid.
		if (it != empireColorEntries.end())
		{
			empireColorEntries.erase(it);
		}

		colorEntry = object_cast<cEmpireColorEntry>(ClassManager.Create(cEmpireColorEntry::NOUN_ID));
		empireColorEntries.emplace(empire->GetEmpireID(), colorEntry);
	}
	colorEntry->SetColor(color);
	colorEntry->SetEmpire(empire);
}

void cEmpireColorManager::DestroyEmpireColorEntry(uint32_t empireID)
{
	auto it = empireColorEntries.find(empireID);

	if (it != empireColorEntries.end())
	{
		it->second->Destroy();
	}
}

void cEmpireColorManager::DestroyEmpireColorEntries()
{
	for (auto& entry : empireColorEntries)
	{
		entry.second->Destroy();
	}
}

Math::ColorRGB cEmpireColorManager::GetEmpireColor(Simulator::cEmpire* empire)
{
	if (empire == nullptr)
	{
		return Math::ColorRGB(1.0f, 1.0f, 1.0f);
	}
	cEmpireColorEntry* empireColorEntry = GetEmpireColorEntry(empire->GetEmpireID());
	if (empireColorEntry != nullptr)
	{
		return empireColorEntry->GetColor();
	}
	cSpeciesProfile* speciesProfile = empire->GetSpeciesProfile();

	if (speciesProfile == nullptr)
	{
		return Math::ColorRGB(1.0f, 1.0f, 1.0f);
	}


	if (empire->GetEmpireID() == StarManager.GetGrobEmpireID())
	{
		return defaultGroxColor;
	}

	Math::ColorRGB color;
	switch (defaultEmpireColorRule) {
	case(EmpireColorRule::base): {
		color = speciesProfile->mSkinColors[0];
		break;
	}
	case(EmpireColorRule::coat): {
		color = speciesProfile->mSkinColors[1];
		break;
	}
	case(EmpireColorRule::detail): {
		color = speciesProfile->mSkinColors[2];
		break;
	}
	case(EmpireColorRule::random): {
		RandomNumberGenerator rng(empire->GetEmpireID());
		color.r = rng.RandomFloat();
		rng.seed++;
		color.g = rng.RandomFloat();
		rng.seed++;
		color.b = rng.RandomFloat();
		break;
	}
	default: {
		color = speciesProfile->mSkinColors[0];
		break;
	}
	}

	return color;
}
