#include "stdafx.h"
#include "cEmpireColorManager.h"

using namespace Simulator;

cEmpireColorManager* cEmpireColorManager::instance = nullptr;

/// AUTOGENERATED METHODS ///

int cEmpireColorManager::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int cEmpireColorManager::Release() {
	return Simulator::cStrategy::Release();
}

const char* cEmpireColorManager::GetName() const {
	return "Empire_Color_Customization::cEmpireColorManager";
}

void cEmpireColorManager::OnModeExited(uint32_t previousModeID, uint32_t newModeID)
{
	if (previousModeID == GameModeIDs::kGameSpace)
	{
		if (!vanillaColorBackup.empty())
		{
			GetCachedColorIdMap() = vanillaColorBackup;
			vanillaColorBackup.clear();
		}
		shouldBackupVanillaColor = true;
		empireColorEntries.clear();
		readDB = false;
		empireColorDB.reset();
	}
}

void cEmpireColorManager::OnModeEntered(uint32_t previousModeID, uint32_t newModeID)
{
	if (newModeID == GameModeIDs::kGameSpace)
	{
		if (!readDB)
		{
			// For some reason, cEmpireColorManager::Read does not execute sometimes when loading a save.
			ReadDB();
		}

	}
}

bool cEmpireColorManager::Write(Simulator::ISerializerStream* stream)
{
	if (!IsSpaceGame())
	{
		return true;
	}
	if (empireColorDB == nullptr)
	{
		if (!InitializeDB())
		{
			ModAPI::Log("Error initializing db");
			return false;
		}
	}
	if (!empireColorDB->Open(IO::AccessFlags::Write, IO::CD::OpenAlways))
	{
		ModAPI::Log("Error opening db for Write");
		return false;
	}
	auto it = empireColorEntries.begin();
	while (it != empireColorEntries.end())
	{
		cEmpireColorEntry* colorEntry = it->second.get();
		if (colorEntry == nullptr)
		{
			it = empireColorEntries.erase(it);
			continue;
		}
		ISerializerWriteStream* writeStream = nullptr;
		ResourceKey key = colorEntry->GetKey();
		if (colorEntry->Valid())
		{
			if (!empireColorDB->OpenWriteStream(key, &writeStream, true))
			{
				ModAPI::Log("Error opening write stream for key %u %u %u", key.instanceID, key.groupID, key.typeID);
				it++;
				continue;
			}
			if (!colorEntry->Write(writeStream))
			{
				ModAPI::Log("Error writing key %u %u %u",
					key.instanceID, key.groupID, key.typeID);
			}
			empireColorDB->CloseWriteStream(writeStream);
			it++;
		}
		else
		{
			empireColorDB->DeleteRecord(key);
			it = empireColorEntries.erase(it);
		}
	}
	if (!empireColorDB->Flush())
	{
		ModAPI::Log("Error flushing db");
	}
	if (!empireColorDB->Close())
	{
		ModAPI::Log("Error closing db");
		return false;
	}
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}

bool cEmpireColorManager::Read(Simulator::ISerializerStream* stream)
{
	if (!readDB)
	{
		ReadDB();
	}
	return readDB && Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

bool cEmpireColorManager::WriteToXML(XmlSerializer*)
{
	return true;
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute cEmpireColorManager::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void cEmpireColorManager::Initialize() {
	instance = this;
	defaultGroxColor = Math::ColorRGB(0.35f, 0.0f, 0.25f);
	shouldBackupVanillaColor = true;
	readDB = false;

	PropertyListPtr managerConfigProp;
	PropManager.GetPropertyList(id("GeneralConfig"), id("EccConfig"), managerConfigProp);
	int defaultEmpireColorRuleInt;
	App::Property::GetInt32(managerConfigProp.get(), 0x1520E05F, defaultEmpireColorRuleInt);
	defaultEmpireColorRule = EmpireColorRule(defaultEmpireColorRuleInt);
}

void cEmpireColorManager::Dispose() {
	
}

void cEmpireColorManager::Update(int deltaTime, int deltaGameTime) {
	
}

cEmpireColorManager* cEmpireColorManager::Get() {
	return instance;
}

EmpireColorRule cEmpireColorManager::GetDefaultEmpireColorRule() const
{
	return defaultEmpireColorRule;
}

bool cEmpireColorManager::InitializeDB()
{
	eastl::string16 path = Resource::Paths::GetSaveArea(Resource::SaveAreaID::GamesGame0)->GetLocation();
	path += u"empireColorCustomizationDB";
	DatabasePackedFilePtr db = new Resource::DatabasePackedFile(path.c_str());
	if (db->Initialize())
	{
		empireColorDB = new SerializerDatabase(db.get());
		return true;
	}
	else
	{
		return false;
	}
}

bool cEmpireColorManager::ReadDB()
{
	if (!IsSpaceGame())
	{
		return true;
	}
	if (empireColorDB == nullptr)
	{
		if (!InitializeDB())
		{
			ModAPI::Log("Error initializing db");
			return false;
		}
	}
	empireColorEntries.clear();
	// For some reason, opening it in read-only mode always fails.
	if (!empireColorDB->Open(IO::AccessFlags::ReadWrite, IO::CD::OpenAlways))
	{
		ModAPI::Log("Error opening db for ReadWrite");
		return false;
	}
	eastl::vector<ResourceKey> keys;
	Resource::StandardFileFilter filter(ResourceKey::kWildcardID, id("Empire_Color_Customization"), cEmpireColorEntry::TYPE);
	empireColorDB->GetKeyList(keys, &filter);
	for (const ResourceKey& key : keys)
	{
		cEmpireColorEntryPtr colorEntry = object_cast<cEmpireColorEntry>(ClassManager.Create(cEmpireColorEntry::NOUN_ID));
		ISerializerReadStream* readStream = nullptr;
		if (!empireColorDB->OpenReadStream(key, &readStream))
		{
			ModAPI::Log("Error opening read stream for key %u %u %u", key.instanceID, key.groupID, key.typeID);
			continue;
		}
		bool success = colorEntry->Read(readStream);
		empireColorDB->CloseReadStream(readStream);

		if (!success)
		{
			ModAPI::Log("Error reading key %u %u %u",
				key.instanceID, key.groupID, key.typeID);
			continue;
		}

		empireColorEntries.emplace(colorEntry->GetEmpireID(), colorEntry);
	}
	if (!empireColorDB->Close())
	{
		ModAPI::Log("Error closing db");
		return false;
	}
	readDB = true;
	return true;
}

cEmpireColorEntry* cEmpireColorManager::GetEmpireColorEntry(uint32_t empireID) const
{
	auto it = empireColorEntries.find(empireID);

	if (it != empireColorEntries.end() && it->second->Valid())
	{
		return it->second.get();
	}

	return nullptr;
}

void cEmpireColorManager::SetEmpireColorEntry(Simulator::cEmpire* empire, Math::ColorRGB color)
{
	if (empire == nullptr)
	{
		return;
	}
	cEmpireColorEntry* colorEntry = nullptr;
	auto it = empireColorEntries.find(empire->GetEmpireID());

	// empireColorEntry exist and it's valid.
	if (it != empireColorEntries.end() && it->second->Valid())
	{
		colorEntry = it->second.get();
	}

	else
	{
		// empireColorEntry exist but isn't valid.
		if (it != empireColorEntries.end())
		{
			empireColorEntries.erase(it);
		}

		colorEntry = object_cast<cEmpireColorEntry>(ClassManager.Create(cEmpireColorEntry::NOUN_ID));
		if (!colorEntry)
		{
			return;
		}
		empireColorEntries.emplace(empire->GetEmpireID(), colorEntry);
	}
	colorEntry->SetColor(color);
	colorEntry->SetEmpire(empire);
}

void cEmpireColorManager::DestroyEmpireColorEntry(uint32_t empireID)
{
	auto it = empireColorEntries.find(empireID);

	if (it != empireColorEntries.end() && it->second)
	{
		it->second->Destroy();
	}
}

void cEmpireColorManager::DestroyEmpireColorEntries()
{
	for (auto& entry : empireColorEntries)
	{
		entry.second->Destroy();
	}
}

Math::ColorRGB cEmpireColorManager::GetVanillaColor(uint32_t colorID)
{
	Math::ColorRGB color;
	auto it = vanillaColorBackup.find(colorID);
	if (it != vanillaColorBackup.end())
	{
		color = it->second;
	}
	else
	{
		// Defaults to white.
		color = Math::ColorRGB(1.0f, 1.0f, 1.0f);
	}
	return color;
}

void cEmpireColorManager::BackupVanillaColors()
{
	vanillaColorBackup = GetCachedColorIdMap();
	shouldBackupVanillaColor = false;
}

Math::ColorRGB cEmpireColorManager::GetEmpireColor(Simulator::cEmpire* empire)
{
	// CachedColorIdMap is also used by the other stages. Since changing empire
	// colors modifies this map, we need to back it up before applying any changes
	// and restore it when leaving the Space Stage.
	if (shouldBackupVanillaColor)
	{
		BackupVanillaColors();
	}
	if (empire == nullptr)
	{
		return Math::ColorRGB(1.0f, 1.0f, 1.0f);
	}
	cEmpireColorEntry* empireColorEntry = GetEmpireColorEntry(empire->GetEmpireID());
	if (empireColorEntry != nullptr)
	{
		return empireColorEntry->GetColor();
	}
	cSpeciesProfile* speciesProfile = empire->GetSpeciesProfile();

	if (speciesProfile == nullptr)
	{
		return Math::ColorRGB(1.0f, 1.0f, 1.0f);
	}


	if (empire->GetEmpireID() == StarManager.GetGrobEmpireID())
	{
		return defaultGroxColor;
	}

	Math::ColorRGB color;
	switch (defaultEmpireColorRule) {
	case(EmpireColorRule::vanilla): {
		// For empires from other saves, their vanilla color seems to always be `mCachedColor`.
		if ((empire->mFlags & EmpireFlags::kEmpireFlagFromSaveGame) != 0 && empire != GetPlayerEmpire())
		{
			color = empire->mCachedColor;

			// No idea if this can happen.
			if (color.r == 0.0f && color.g == 0.0f && color.b == 0.0f)
			{
				// Defaults to coat color.
				color = speciesProfile->mSkinColors[1];
			}
		}
		else
		{
			color = GetVanillaColor(empire->mIDColorID);
			// If the color is white, then no color was found.
			if (color.r == 1.0f && color.g == 1.0f && color.b == 1.0f)
			{
				// Defaults to coat color.
				color = speciesProfile->mSkinColors[1];
			}
		}
		break;
	}
	case(EmpireColorRule::base): {
		color = speciesProfile->mSkinColors[0];
		break;
	}
	case(EmpireColorRule::coat): {
		color = speciesProfile->mSkinColors[1];
		break;
	}
	case(EmpireColorRule::detail): {
		color = speciesProfile->mSkinColors[2];
		break;
	}
	case(EmpireColorRule::random): {
		RandomNumberGenerator rng(empire->GetEmpireID());
		color.r = rng.RandomFloat();
		rng.seed++;
		color.g = rng.RandomFloat();
		rng.seed++;
		color.b = rng.RandomFloat();
		break;
	}
	default: {
		color = speciesProfile->mSkinColors[0];
		break;
	}
	}

	return color;
}
