#include "stdafx.h"
#include "cEmpireColorEntry.h"
using namespace Simulator;

/// AUTOGENERATED METHODS ///

size_t cEmpireColorEntryFactory::GetTypes(uint32_t* pDstTypes, size_t count) const {
	if (count >= 1) {
		pDstTypes[0] = cEmpireColorEntry::NOUN_ID;
		return 1;
	}
	return 0;
}
Object* cEmpireColorEntryFactory::Create(uint32_t type, ICoreAllocator* pAllocator) {
	return new cEmpireColorEntry();
}
const char* cEmpireColorEntryFactory::GetName(uint32_t type) const {
	return "cEmpireColorEntry";
}


int cEmpireColorEntry::AddRef() {
	return DefaultRefCounted::AddRef();
}
int cEmpireColorEntry::Release() {
	return DefaultRefCounted::Release();
}
uint32_t cEmpireColorEntry::GetNounID() const {
	return NOUN_ID;
}

void* cEmpireColorEntry::Cast(uint32_t type) const {
	CLASS_CAST(cEmpireColorEntry);
	//PARENT_CAST(Simulator::ISimulatorSerializable);
	return nullptr;
}

bool cEmpireColorEntry::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool cEmpireColorEntry::Read(Simulator::ISerializerStream* stream)
{
	auto ret = Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
	if (ret)
	{
		empire = StarManager.GetEmpire(empireID);
	}
	return ret;
}

bool cEmpireColorEntry::ISimulatorSerializable_func18h()
{
	return true;
}

bool cEmpireColorEntry::WriteToXML(Simulator::XmlSerializer*)
{
	return true;
}

Simulator::Attribute cEmpireColorEntry::ATTRIBUTES[] = {
	SimAttribute(cEmpireColorEntry, empireID, 0),
	SimAttribute(cEmpireColorEntry, color, 1),
	Simulator::Attribute()
};

uint32_t cEmpireColorEntry::GetEmpireID() const
{
	return empireID;
}

Math::ColorRGB cEmpireColorEntry::GetColor() const
{
	return color;
}

void cEmpireColorEntry::SetColor(Math::ColorRGB color)
{
	this->color = color;
}

cEmpire* cEmpireColorEntry::GetEmpire() const
{
	return empire.get();
}

void cEmpireColorEntry::SetEmpire(cEmpire* empire)
{
	this->empire = empire;
	if (empire != nullptr)
	{
		this->empireID = empire->GetEmpireID();
	}
	else
	{
		this->empireID = 0;
	}
}

ResourceKey cEmpireColorEntry::GetKey() const
{
	return ResourceKey(empireID, cEmpireColorEntry::TYPE, id("Empire_Color_Customization"));
}

bool cEmpireColorEntry::Valid() const
{
	return !destroyed && empire != nullptr && empire->mStars.size() > 0;
}

void cEmpireColorEntry::Destroy()
{
	destroyed = true;
}
